name: Moto GPS Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4        # ✅ v3 → v4

      - name: Setup Java
        uses: actions/setup-java@v4      # ✅ v3 → v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Configure local.properties
        run: |
          mkdir -p ~/.gradle
          echo "MAPBOX_DOWNLOADS_TOKEN=${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}" >> ~/.gradle/gradle.properties
          echo "sdk.dir=$ANDROID_HOME" >> android/local.properties
          echo "flutter.sdk=$FLUTTER_ROOT" >> android/local.properties
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> android/local.properties

      - name: Fix AndroidX
        run: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=false" >> android/gradle.properties

      - name: Clean Gradle cache
        run: |
          rm -rf ~/.gradle/caches/transforms-3
          rm -rf ~/.gradle/caches/modules-2

      - name: Delete auto-generated files
        run: |
          rm -f android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
          rm -f .flutter-plugins
          rm -f .flutter-plugins-dependencies

      - name: Install dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Clean Gradle
        run: |
          flutter clean
          cd android && ./gradlew clean --no-daemon || true
          cd ..
      
      - name: Build AAB Release
        run: flutter build apk --release --dart-define=MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
          GRADLE_OPTS: "-Xmx4g -XX:MaxMetaspaceSize=512m"
          JAVA_TOOL_OPTIONS: "-Xmx4g"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # ✅ ya estaba en v4
        with:
          name: release-apk
          path: build/app/outputs/bundle/release/app-release.aab
